# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fanfeedr}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Johnny Khai Nguyen"]
  s.date = %q{2010-05-16}
  s.description = %q{Ruby wrapper for the Fanfeedr API}
  s.email = %q{johnnyn@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "generators/fanfeedr/USAGE",
     "generators/fanfeedr/fanfeedr_generator.rb",
     "init.rb",
     "install.rb",
     "lib/fanfeedr.rb",
     "lib/fanfeedr/client.rb",
     "tasks/fanfeedr_tasks.rake",
     "test/fanfeedr_test.rb",
     "test/fixtures/geo_feed.json",
     "test/fixtures/league_scores.json",
     "test/fixtures/ncaab_boxscore.json",
     "test/fixtures/resource_feed.json",
     "test/fixtures/schedule.json",
     "test/fixtures/schedule_resource.json",
     "test/fixtures/score_resource.json",
     "test/fixtures/team_scores.json",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/phuphighter/fanfeedr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby wrapper for the Fanfeedr API}
  s.test_files = [
    "test/fanfeedr_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.0"])
    else
      s.add_dependency(%q<httparty>, [">= 0.5.0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.5.0"])
  end
end

